[package]
name = "video-processing-service"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.0"
base64 = "0.22.1"
object_store = { version = "0.12.0", features = ["gcp"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"